version: "3"
volumes:
  node_modules:
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "password"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build: .
    env_file: .env
    # following command addresses this issue with bcrypt module https://github.com/riverrun/comeonin/issues/64
    command: bash -c "mix deps.get && (cd deps/bcrypt_elixir && make clean && make) && mix deps.compile && mix phx.server"
    volumes:
      - .:/app
      - node_modules:/app/assets/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - db
