version: "3"
volumes:
  node_modules:
  build:
services:
  db:
    image: postgres:11-alpine
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
  server:
    build: .
    env_file: .env
    command: mix phx.server
    volumes:
      - .:/app
      - node_modules:/app/assets/node_modules
      - build:/app/_build
    ports:
      - "4000:4000"
    depends_on:
      - db
